name: ci

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PHP lint
        run: |
          for file in $(find . -name "*.php"); do
            php -l "$file"
          done
